version: 2.1
orbs:
  cypress: cypress-io/cypress@1.0.0
  
jobs:
      # checks out code and installs dependencies once
      - cypress/install:
          name: 'Linux install'
          # and builds the app using this command
          build: 'npm run build'
          post-steps:
            # show Cypress cache folder and binary versions
            # to check if we are caching previous binary versions
            - run: npx cypress cache path
            - run: npx cypress cache list
            - run: npx cypress info
      - cypress/run:
          name: '2 machines using Chrome'
          # job will use workspace with code and dependencies
          # installed by the "install" job
          requires:
            - Linux install
          # use executor with Chrome installed
          executor: cypress/browsers-chrome76
          # use browser "chrome" for running tests
          browser: chrome
          record: false
          parallel: false
          group: '2x-chrome on CircleCI'
          start: 'npm run start:ci'

      
workflows:
  win-build:
    jobs:
      - win-test

