version: 2.1
orbs:
  cypress: cypress-io/cypress@1.0.0
jobs:
  win-test:
    working_directory: ~/app
    executor:
      name: win/vs2019
      shell: bash.exe
    steps:
      - checkout

      - restore_cache:
          key: dependencies-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}

      - run: npm ci
      - run: npm run cy:verify
      - run: npm run cy:info
      
workflows:
  win-build:
    jobs:
      - win-test
